<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2011/12/15 10:08:46

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=test_nainit',
  'username' => 'trainee',
  'password' => 'trainee',
  'name' => 'doctrine',
)),);
