<?php
// auto-generated by sfSecurityConfigHandler
// date: 2011/12/15 10:08:46
$this->security = array (
  'register' => 
  array (
    'is_secure' => false,
  ),
  'forgetpassword' => 
  array (
    'is_secure' => false,
  ),
  'all' => 
  array (
    'is_secure' => true,
  ),
);
